version: 2.1
orbs:
  node: circleci/node@4.7
  codecov: codecov/codecov@1.0.1
# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: cimg/node:18.16
    steps:
      - checkout
      - node/install-packages:
        pkg-manager: npm
      - run: npm run build
  test:
    docker:
      - image: cimg/node:18.16
    steps:
      - checkout
      - node/install-packages:
        pkg-manager: npm
      - run: npm test
      - store_artifacts:
        path: coverage/coverage-final.json
        destination: coverage.json
      - codecov/upload:
          name: Upload coverage reports to Codecov
          file: ./coverage.json
          token: $CODECOV_TOKEN

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
